### ISSUE TITLE
TexGen GUI

### ISSUE THREAD

**Issue by Gyorgy51** [louisepb/TexGenScripts#1]
Hi,

I have downloaded the TexGen 3.11 boundle and installed. Unfortunately the double click on the TexGen icon does nothing. Then based on some blog information I have installed TexGen 3.10. Unfortunately TexGenGui exe does not start either. 
As I know there are no prerequisites in case of the boundle because it has the necessary Python dll.
My computer is a 64 bit Winndos 7. 
What can be the problem? Could you help how could I debug?
Thank you in advance. Kind regards

Gyorgy

**Comment by Gyorgy51** [comment]
I have tried 3.11 Windows 7 64 bit on my other computer but unfortunately nothing happens after strating Texgengui exe. Unfortunately there is no error message from which i could find out what is wrong. Please edvice me what to do. Thank you

**Comment by Gyorgy51** [comment]
Is there any way to integrate TextGen int Simulia?

**Comment by Gyorgy51** [comment]
I tried TexGen 3.10 boundle as well but unfortunately it does not work either. I tried the installtion on 2 of my 64 bit Windows 7 computer. The problem is the same. The GUI does not start end even it does not leave any error message.

**Comment by louisepb** [comment]
Many apologies for not responding to this sooner - I only just spotted your messages.

There seems to be a problem with the recentbundles versions using Python 27 on some machines. I think that there is a Python file missing but unfortunately I've been unable as yet to identify what the problem is. You could try installing Python 27 on your computer from www.python.org. In most cases this seem to solve the problem (which somewhat defeats the object of having a bundled version!). Hopefully this will work for you. If not, the Python26 version here https://sourceforge.net/projects/texgen ... en/3.10.0/ seems to install successfully on most machines.

As far as integrating TexGen with Simulia goes you can use the Python API to call TexGen functions from within ABAQUS as long as you are using a version built with a compatible version of Python.  For recent versions of ABAQUS this needs to be Python 27.  Even if you haven't got the GUI working the TexGen core python library should still work ok

Hope that helps,
Louise

**Comment by louisepb** [comment]
Issue solved - bundled installation now adds PythonPath registry key for Python 2.7 so that works even if Python not installed
